### ISSUE TITLE
Switch to React 0.13

### ISSUE THREAD

**Issue by ryanlanciaux** [DynamicTyped/Griddle#111]

**Comment by benmosher** [comment]
Do you have a sense of what the timeframe is for this?

Since you loosened the `peerDependencies` version, I have attempted to use v0.2.11 with React v0.13.1, but without success, and given a half hour of prodding, it was not clear to me what the issue is (i.e., is it Griddle proper, or the way I'm using it, or...).

I'm curious if you all have been able to use it with React 0.13?

**Comment by ryanlanciaux** [comment]
@benmosher This should be all set now. Please let me know if you are still running into trouble. :+1:
