### ISSUE TITLE
Gruntfile.js is ignored in .npmignore

### ISSUE THREAD

**Issue by RusAlex** [DynamicTyped/Griddle#52]
Therefore steps from README

```README
npm install -g grunt-cli
npm install
grunt
```

Do not work.

**Comment by ryanlanciaux** [comment]
Hey thanks for the feedback! The thought with grunt is that it would only be used against the source. We didn't want to ship the Gruntfile when someone includes the `griddle-react` component in their project.

**Comment by RusAlex** [comment]
Anyway README instructions from index does not work.

**Comment by ryanlanciaux** [comment]
Sorry to hear it's not working for you! Are you receiving any error messages? 

Just to make sure that we weren't missing something, I tried to run Griddle from the repository:

1. `git clone https://github.com/DynamicTyped/Griddle.git`
1. `cd Griddle`
1. `npm install`
1. `grunt`

And didn't encounter any issues. Please let us know what you're running into and we'll try to get it sorted out :+1:

**Comment by RusAlex** [comment]
Sure in repository is OK. But your README file instructions 
says to use npm.

As long as Gruntfile.js is ignored in .npmignore , 
this file does not come with 
```shell
'npm install griddle'
```

command.

And therefore

```shell
grunt
```

Does not work.

**Comment by ryanlanciaux** [comment]
Thanks for posting! :+1:  We did have an issue if a project included underscore that we have since resolved. 

In regard to the Gruntfile... The thought is if someone is using the module from npm there is some other build tool already in place. To that end, we do not want to force people into using Grunt so including the Gruntfile is not something that we will be doing. Please see [an example with Gulp](https://github.com/ryanlanciaux/griddle-gulp-test) or [this webpack example](https://github.com/ryanlanciaux/griddle-webpack-test) for more on this. 

I'm going to close this for now but please feel free to get back to us if you're still encountering any problems! :+1:
